[tool.poetry]
name = "broken-down-model"
version = "0.1.0"
description = "A set of utlities for breaking a large Django model down to separate components"
authors = ["Shai Berger <shai.berger@slatescience.com>"]
license = "MIT"
packages = [
    {include = "bdmodels"},
]
exclude = ["bdmodels/tests.py"]

[tool.poetry.dependencies]
python = "^3.7"
django = "^2.2.22"

[tool.poetry.dev-dependencies]
ipython = "*"
flake8 = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
