[tool.poetry]
name = "broken-down-model"
version = "0.1.0"
description = "A set of utlities for breaking a large Django model down to separate components"
authors = ["Shai Berger <shai.berger@slatescience.com>"]
license = "MIT"
packages = [
    {include = "bdmodels"},
]
exclude = ["bdmodels/tests.py"]

[tool.poetry.dependencies]
python = "^3.7"
django = ">= 2.2"

[tool.poetry.dev-dependencies]
ipython = "*"
flake8 = "*"
tox = "^3.23.1"
Sphinx = "^4.0.2"
sphinx-rtd-theme = "^0.5.2"


[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py{37,38,39}-django{22,31,32}
isolated_build = True
skipsdist = True

[testenv]
deps =
    django22: Django>=2.2,<2.3
    django31: Django>=3.1,<3.2
    django32: Django>=3.2,<3.3

changedir = test_bdmodels

commands =
    python manage.py test bdmodels testapp testmigs
"""

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
