# Generated by Django 2.2.20 on 2021-04-18 10:02

import bdmodels.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentA',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('para_name', models.CharField(max_length=10)),
                ('para_zit', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParentB',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('parb_name', models.CharField(max_length=10)),
                ('parb_zit', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParentC',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('parc_name', models.CharField(max_length=10)),
                ('parc_zit', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParentWithFK',
            fields=[
                ('fkid', models.AutoField(primary_key=True, serialize=False)),
                ('parfk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Nephew',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserChild',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('child_name', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('child_name', models.CharField(max_length=10)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
