# Generated by Django 2.2.19 on 2021-04-04 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParentA',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('para_name', models.CharField(max_length=10)),
                ('para_zit', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParentB',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('parb_name', models.CharField(max_length=10)),
                ('parb_zit', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParentC',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('parc_name', models.CharField(max_length=10)),
                ('parc_zit', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('parentc_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='testapp.ParentC')),
                ('parentb_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='testapp.ParentB')),
                ('parenta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='testapp.ParentA')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('child_name', models.CharField(max_length=10)),
            ],
            bases=('testapp.parenta', 'testapp.parentb', 'testapp.parentc'),
        ),
    ]
