# Generated by Django 2.2.20 on 2021-04-06 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartialChild',
            fields=[
                ('parenta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='testapp.ParentA')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('child_name', models.CharField(max_length=10)),
                ('parentb_ptr', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, to='testapp.ParentB')),
                ('parentc_ptr', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, parent_link=True, to='testapp.ParentC')),
            ],
            options={
                'abstract': False,
            },
            bases=('testapp.parenta', 'testapp.parentb', 'testapp.parentc', models.Model),
        ),
    ]
