# Generated by Django 2.2.21 on 2021-05-10 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_timestampedchild'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('testapp.child',),
        ),
    ]
