# Generated by Django 2.2.23 on 2021-05-24 18:24

import bdmodels.fields
from django.db import migrations, models
from bdmodels import migration_ops


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_childproxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildWithVirtualNonParent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('child_name', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migration_ops.AddVirtualField(
            model_name='ChildWithVirtualNonParent',
            name='parenta_ptr',
            field=bdmodels.fields.VirtualParentLink(from_field='id', on_delete=models.DO_NOTHING, to='testapp.ParentA'),
        ),
        migration_ops.AddVirtualField(
            model_name='ChildWithVirtualNonParent',
            name='b',
            field=bdmodels.fields.VirtualOneToOneField(from_field='id', on_delete=models.DO_NOTHING, to='testapp.ParentB')
        ),
    ]
