# Generated by Django 2.2.20 on 2021-04-07 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testapp', '0004_userchild'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentWithFK',
            fields=[
                ('fkid', models.AutoField(primary_key=True, serialize=False)),
                ('parfk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Nephew',
            fields=[
                ('parentwithfk_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='testapp.ParentWithFK')),
                ('parenta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testapp.ParentA')),
            ],
            options={
                'abstract': False,
            },
            bases=('testapp.parenta', 'testapp.parentwithfk', models.Model),
        ),
    ]
