# Generated by Django 2.2.20 on 2021-04-14 09:56

import bdmodels.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testapp', '0005_nephew_parentwithfk'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualChild',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('child_name', models.CharField(max_length=10)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.SeparateDatabaseAndState(state_operations=[
            migrations.AddField(
                model_name='virtualchild',
                name='parenta_ptr',
                field=bdmodels.fields.VirtualOneToOneField2(db_index=False, editable=False, from_field='id', on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, to='testapp.ParentA'),
                preserve_default=False,
            ),
            migrations.AddField(
                model_name='virtualchild',
                name='parentb_ptr',
                field=bdmodels.fields.VirtualOneToOneField2(db_index=False, editable=False, from_field='id', on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, to='testapp.ParentB'),
                preserve_default=False,
            ),
            migrations.AddField(
                model_name='virtualchild',
                name='parentc_ptr',
                field=bdmodels.fields.VirtualOneToOneField2(db_index=False, editable=False, from_field='id', on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, to='testapp.ParentC'),
                preserve_default=False,
            ),
        ]),
    ]
