# Generated by Django 2.2.23 on 2021-07-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BigModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.BooleanField(default=True)),
                ('b', models.BooleanField(null=True)),
                ('c', models.IntegerField(default=3)),
                ('d', models.CharField(default='hi', max_length=10)),
            ],
        ),
    ]
