# Generated by Django 2.2.23 on 2021-07-07 15:14

import bdmodels.fields
from django.db import migrations, models
import django.db.models.deletion

from bdmodels import migration_ops


class Migration(migrations.Migration):

    dependencies = [
        ('testmigs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partial',
            fields=[
                ('partial_id', models.IntegerField(primary_key=True, serialize=False)),
                ('c', models.IntegerField(default=3)),
                ('d', models.CharField(default='hi', max_length=10)),
            ],
        ),
        migration_ops.AddVirtualField(
            model_name='bigmodel',
            name='partial_ptr',
            field=bdmodels.fields.VirtualParentLink(from_field='id', on_delete=django.db.models.deletion.PROTECT, to='testmigs.Partial'),
        ),
    ]
