# Generated by Django 2.2.23 on 2021-07-07 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testmigs', '0003_copy_big_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bigmodel',
            name='c',
        ),
        migrations.RemoveField(
            model_name='bigmodel',
            name='d',
        ),
    ]
